on:
  - push
  - pull_request
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Checkout
        uses: actions/checkout@v4

      - name: ci.sh
        run: nix develop --command ./ci.sh
