on:
  - push
  - pull_request
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ci.sh
        run: nix develop --command ./ci.sh
